# Runs formatting requirements
name: Java Formatting

on:
  push:
    branches:
      - master
    paths: ['src/main/java/**', 'src/test/**']
  pull_request:
    paths: ['src/main/java/**', 'src/test/**']

concurrency:
  group: format-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Run Spotless Formatting Check with Gradle
        id: build
        run: ./gradlew --info spotlessCheck

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          message: spotlessApply
          author_name: Github Actions
          author_email: actions@github.com
          add: "*.java"

      - name: Pull Requests
        if: ${{ failure() }}
        run: |
          gh pr create \
            --head "${FIXED_BRANCH}" \
            --base "${PR_BRANCH}" \
            --title "Spotless apply for branch ${{ github.event.pull_request.head.ref }} for #${{ github.event.pull_request.number }}" \
            --body "Automatic spotless apply to fix formatting errors, applies to PR #${{ github.event.pull_request.number }}" \
            2>&1 | tee pr-message.log || true
          gh pr comment "${PR_BRANCH}" -F pr-message.log || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BRANCH: ${{ github.head_ref }}
          FIXED_BRANCH: ${{ github.head_ref }}-spotless-fixes
